[pytest]
DJANGO_SETTINGS_MODULE = backend.settings
python_files = tests.py test_*.py *_tests.py
addopts = backend
testpaths = backend


; [pytest]
; DJANGO_SETTINGS_MODULE = backend.settings
; python_files = tests.py test_*.py *_tests.py


; testpaths = backend


; norecursedirs = 
;     frontend
;     vendor
;     node_modules
;     dist
;     build
;     .git
;     .*