# Generated by Django 5.1.6 on 2025-10-02 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('GRAIN', 'Grain'), ('DAIRY', 'Dairy'), ('PROTEIN', 'Protein'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('storage_type', models.CharField(max_length=50)),
                ('expiration_date', models.DateTimeField()),
                ('date_opened', models.DateTimeField(blank=True, null=True)),
                ('date_frozen', models.DateTimeField(blank=True, null=True)),
                ('date_purchased', models.DateTimeField()),
                ('isMeal', models.BooleanField()),
                ('date_refridgerated', models.DateTimeField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('unit', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
