# Generated by Django 5.1.6 on 2025-10-02 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_fooditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='storage_type',
            field=models.CharField(choices=[('FRIDGE', 'Refridgerator'), ('FREEZER', 'Freezer'), ('PANTRY', 'Pantry'), ('COUNTER', 'Counter')], max_length=30),
        ),
    ]
